(function(){'use strict';
const A=window.JC_APP,ctx=window.JC_ATTENDANT_CONTEXT||{},$=id=>document.getElementById(id);let unlocked=false;
function toast(text){const fn=window.toast;if(typeof fn==='function')try{return fn(text)}catch(e){}alert(text)}
function fixedSignature(settings){const s=ctx.signature||{};settings.developerShow=s.show!==false;settings.developerName=s.name||'JC-APK TV';settings.developerWhatsapp=String(s.whatsapp||'5555997234936').replace(/\D/g,'');settings.developerInstagram=s.instagram||'';settings.developerMessage=s.message||'Desenvolvido por JC-APK TV';return settings}
function localSettings(){try{return JSON.parse(localStorage.getItem(ctx.storageKey)||'{}')}catch(e){return {}}}
async function syncSettings(){if(!ctx.configMode)return;if(ctx.testMode){toast('Modo teste: a configuração foi simulada, mas não foi publicada.');return}const access=ctx.access||await A.myAccess();if(!access?.profile)throw new Error('Sessão não encontrada.');const settings=fixedSignature(localSettings());const {error}=await A.client.from('attendant_profiles').update({public_settings:settings,published:true}).eq('user_id',access.profile.id);if(error)throw error;toast('Configurações salvas no seu acesso e publicadas no link dos seus clientes.')}
function hidePublicAdmin(){if(ctx.configMode)return;const b=$('adminBtn');if(b)b.style.display='none';const m=$('adminModal');if(m)m.remove()}
function addPublicLink(){if(!ctx.configMode)return;const panel=$('panel-settings');if(!panel||$('jc_attendant_account_box'))return;const box=document.createElement('section');box.id='jc_attendant_account_box';box.style.cssText='margin:14px 0;padding:14px;border-radius:14px;border:1px solid rgba(77,163,255,.3);background:rgba(77,163,255,.07)';const base=A.cfg.attendantUrl||location.origin+location.pathname;const link=base+'?cliente='+encodeURIComponent(ctx.slug);box.innerHTML=`<h3 style="margin-top:0">Acesso e link público</h3><p style="color:var(--muted)">Depois de salvar, este é o link que você coloca nas redes sociais. Os clientes veem somente a atendente configurada.</p><input id="jc_public_link" readonly value="${link}" style="width:100%;padding:11px;border-radius:10px;border:1px solid var(--line);background:rgba(0,0,0,.2);color:#fff"><button id="jc_copy_public_link" type="button" class="ghost-btn" style="margin-top:8px">Copiar link público</button><hr style="border:0;border-top:1px solid var(--line);margin:15px 0"><h3>Senha das configurações</h3><p style="color:var(--muted)">Essa senha protege somente a edição da atendente. A senha escolhida não fica visível para o administrador.</p><div style="display:grid;grid-template-columns:1fr 1fr;gap:8px"><input id="jc_att_pass1" type="password" placeholder="Nova senha (mín. 8)" style="padding:11px;border-radius:10px;border:1px solid var(--line);background:rgba(0,0,0,.2);color:#fff"><input id="jc_att_pass2" type="password" placeholder="Confirmar senha" style="padding:11px;border-radius:10px;border:1px solid var(--line);background:rgba(0,0,0,.2);color:#fff"></div><button id="jc_save_att_pass" type="button" class="primary-btn" style="margin-top:8px">Salvar senha das configurações</button>`;panel.prepend(box);$('jc_copy_public_link').onclick=()=>navigator.clipboard.writeText(link).then(()=>toast('Link público copiado.'));$('jc_save_att_pass').onclick=saveConfigPassword}
async function saveConfigPassword(){const a=$('jc_att_pass1').value,b=$('jc_att_pass2').value;if(a.length<8)return toast('A senha precisa ter pelo menos 8 caracteres.');if(a!==b)return toast('As senhas não conferem.');const {error}=await A.client.rpc('set_attendant_password',{p_password:a});if(error)return toast(error.message);$('jc_att_pass1').value=$('jc_att_pass2').value='';unlocked=true;toast('Senha das configurações salva.')}
function passwordModal(){let m=$('jc_att_password_gate');if(m)return m;m=document.createElement('div');m.id='jc_att_password_gate';m.style.cssText='display:none;position:fixed;inset:0;z-index:99999999;align-items:center;justify-content:center;background:rgba(0,0,0,.78);padding:10px';m.innerHTML='<div style="width:min(430px,100%);padding:22px;border-radius:20px;border:1px solid rgba(255,255,255,.14);background:#0b1d29;color:#fff"><h3>Senha das configurações</h3><p style="color:#aebbc3">Digite a senha criada para editar sua atendente.</p><input id="jc_att_gate_input" type="password" style="width:100%;padding:11px;border-radius:10px;border:1px solid rgba(255,255,255,.14);background:#06131b;color:#fff"><div id="jc_att_gate_msg" style="min-height:20px;color:#ff9ba8;margin-top:7px"></div><div style="display:flex;gap:7px"><button id="jc_att_gate_cancel" style="flex:1;padding:10px;border-radius:10px;border:0">Cancelar</button><button id="jc_att_gate_ok" style="flex:1;padding:10px;border-radius:10px;border:0;background:#25d366;color:#052117;font-weight:900">Entrar</button></div></div>';document.body.appendChild(m);$('jc_att_gate_cancel').onclick=()=>m.style.display='none';$('jc_att_gate_ok').onclick=verifyGate;return m}
async function verifyGate(){const p=$('jc_att_gate_input').value;const {data,error}=await A.client.rpc('verify_attendant_password',{p_password:p});if(error||!data){$('jc_att_gate_msg').textContent=error?.message||'Senha incorreta.';return}unlocked=true;$('jc_att_password_gate').style.display='none';$('adminBtn').click()}
function protectAdmin(){if(!ctx.configMode||ctx.testMode)return;const configured=Boolean(ctx.access?.attendant?.password_configured);if(!configured){unlocked=true;return}document.addEventListener('click',e=>{const b=e.target.closest('#adminBtn');if(!b||unlocked)return;e.preventDefault();e.stopPropagation();e.stopImmediatePropagation();const m=passwordModal();m.style.display='flex';setTimeout(()=>$('jc_att_gate_input').focus(),30)},true)}

function lockSignatureUI(){
  const fields=$('developerProtectedFields');
  if(fields) fields.disabled=true;
  const pin=$('developerPinInput'),unlock=$('unlockDeveloperSettings'),lock=$('lockDeveloperSettings');
  if(pin) pin.closest('.brand-lock-row')?.remove();
  if(unlock) unlock.remove();
  if(lock) lock.remove();
  const status=$('developerLockStatus');
  if(status){status.textContent='🔐 Assinatura protegida. Somente o administrador altera no painel JC-APK TV.';status.style.color='var(--green)'}
}
function bindSave(){const b=$('saveSettings');if(!b)return;b.addEventListener('click',()=>setTimeout(()=>syncSettings().catch(e=>toast('Não foi possível publicar: '+e.message)),120))}
function rewriteStorageKeys(){/* As chaves já são definidas no HTML usando JC_ATTENDANT_CONTEXT. */}
function init(){hidePublicAdmin();lockSignatureUI();addPublicLink();protectAdmin();bindSave();rewriteStorageKeys();if(ctx.configMode&&ctx.testMode){const panel=$('panel-settings');if(panel){const n=document.createElement('div');n.style.cssText='padding:10px;border:1px solid rgba(255,191,71,.3);background:rgba(255,191,71,.08);border-radius:12px;margin-bottom:12px;color:#ffe5a6';n.textContent='MODO TESTE — você pode simular as configurações, mas elas não serão publicadas.';panel.prepend(n)}}}
if(document.readyState==='loading')document.addEventListener('DOMContentLoaded',init);else init();
})();
